Repository isengrims/PetriNets, pull requests merged in 2019-06, with the labels that each got.

#31 Сделано добавление моделей на основе объектов View
  PetriNets/PetriNet.Designer.cs
  PetriNets/PetriNet.cs
  PetriNetsClassLibrary/CTransition.cs
  PetriNetsClassLibrary/Edge.cs
  PetriNetsClassLibrary/MArc.cs
  PetriNetsClassLibrary/MTransition.cs
  PetriNetsClassLibrary/PetriNetsClassLibrary.csproj
Labels: Model, Story, View

#33 Добавлено удаление объектов View и соответсвующих им объектов Model
  PetriNets/PetriNet.cs
  PetriNetsClassLibrary/CPlace.cs
  PetriNetsClassLibrary/CTransition.cs
Labels: Controller, Model, Story, View

#35 Добавлена отрисовка меток в Place
  PetriNets/PetriNet.cs
  PetriNetsClassLibrary/MArc.cs
  PetriNetsClassLibrary/MPlace.cs
Labels: View

#40 Исправлена некорректная работа отображения объектов при вызове контекстного меню
  PetriNets/PetriNet.cs
Labels: View, improvment

#41 Реализовано сохранение и открытие сети
  PetriNets/PetriNet.Designer.cs
  PetriNets/PetriNet.cs
  PetriNets/PetriNet.resx
  PetriNets/PetriNets.csproj
  PetriNets/Properties/Resources.Designer.cs
  PetriNets/Properties/Resources.resx
  PetriNets/Resources/36792-3-folders-file.png
  PetriNets/Resources/computer-icons-icon-design-iconfinder-save-icon.jpg
  PetriNetsClassLibrary/Edge.cs
  PetriNetsClassLibrary/MArc.cs
  PetriNetsClassLibrary/MPlace.cs
  PetriNetsClassLibrary/MTransition.cs
  PetriNetsClassLibrary/Model.cs
Labels: Model, Story, View

#43 Реализован режим выполнения сети Петри
  PetriNets/PetriNet.Designer.cs
  PetriNets/PetriNet.cs
  PetriNets/PetriNet.resx
  PetriNets/PetriNets.csproj
  PetriNets/Properties/Resources.Designer.cs
  PetriNets/Properties/Resources.resx
  PetriNets/Resources/Animation mode.png
  PetriNets/Resources/line1.png
  PetriNetsClassLibrary/CTransition.cs
  PetriNetsClassLibrary/MTransition.cs
  PetriNetsClassLibrary/PetriNet.cs
Labels: Controller, Story, View

#62 Созданы unit тесты для методов контроллера CTransition
  PetriNetTests/PetriNetTest.cs
  PetriNetTests/PetriNetTests.csproj
  PetriNets/PetriNet.cs
Labels: Auto Test

#64 Добавлено рандомное выполнение сети
  PetriNets/PetriNet.Designer.cs
  PetriNets/PetriNet.cs
  PetriNets/PetriNets.csproj
  PetriNets/Properties/Random.png
  PetriNets/Properties/Resources.Designer.cs
  PetriNets/Properties/Resources.resx
Labels: improvment, Переход
